"""empty message

Revision ID: 0875a03a4c83
Revises: cd1e7036e4e0
Create Date: 2018-11-26 13:33:53.986299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0875a03a4c83'
down_revision = 'cd1e7036e4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'stocks', 'users', ['userStocksID'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    # ### end Alembic commands ###
