"""empty message

Revision ID: 0c9a06936b70
Revises: 34d6180e603f
Create Date: 2018-11-24 14:20:29.251706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9a06936b70'
down_revision = '34d6180e603f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('catPackageID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'packages', 'category', ['catPackageID'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'packages', type_='foreignkey')
    op.drop_column('packages', 'catPackageID')
    # ### end Alembic commands ###
