"""empty message

Revision ID: 24d7329b0495
Revises: a706abe2f1f6
Create Date: 2018-12-01 10:12:14.441305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24d7329b0495'
down_revision = 'a706abe2f1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages_track', sa.Column('code', sa.String(length=255), nullable=True))
    op.drop_column('packages_track', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages_track', sa.Column('notes', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('packages_track', 'code')
    # ### end Alembic commands ###
