"""empty message

Revision ID: 2cfa82418744
Revises: 630045d8a70f
Create Date: 2018-11-26 09:19:35.745422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cfa82418744'
down_revision = '630045d8a70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PODetails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('POID', sa.Integer(), nullable=False),
    sa.Column('packageID', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['POID'], ['PO.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['packageID'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('po_details')
    # ### end Alembic commands ###
