"""empty message

Revision ID: 382c2d6321d7
Revises: 06d22662a294
Create Date: 2018-11-23 16:49:15.016044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382c2d6321d7'
down_revision = '06d22662a294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_ibfk_2', 'items', type_='foreignkey')
    op.drop_constraint('items_ibfk_1', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'category', ['catID'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'items', 'users', ['userItem'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_ibfk_1', 'items', 'category', ['catID'], ['id'])
    op.create_foreign_key('items_ibfk_2', 'items', 'users', ['userItem'], ['id'])
    # ### end Alembic commands ###
