"""empty message

Revision ID: 4d54ec49ec5e
Revises: da76fbccf927
Create Date: 2018-11-27 06:44:21.810825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d54ec49ec5e'
down_revision = 'da76fbccf927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PO',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplierID', sa.Integer(), nullable=False),
    sa.Column('userPOID', sa.Integer(), nullable=False),
    sa.Column('packagePOID', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('buyingPricePerPackage', sa.Float(), nullable=True),
    sa.Column('totalPrice', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['packagePOID'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplierID'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userPOID'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userSalesID', sa.Integer(), nullable=False),
    sa.Column('customerSalesID', sa.Integer(), nullable=False),
    sa.Column('packageSalesID', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sellingPricePerPackage', sa.Float(), nullable=False),
    sa.Column('totalPrice', sa.Float(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customerSalesID'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['packageSalesID'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userSalesID'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('PO')
    # ### end Alembic commands ###
