"""empty message

Revision ID: 59438e891798
Revises: 037e03ac4b11
Create Date: 2018-11-25 12:40:47.793759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59438e891798'
down_revision = '037e03ac4b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('packagesID', sa.Integer(), nullable=False),
    sa.Column('beginning', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['packagesID'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PO',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplierID', sa.Integer(), nullable=False),
    sa.Column('stockID', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stockID'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplierID'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PO')
    op.drop_table('stocks')
    # ### end Alembic commands ###
