"""empty message

Revision ID: 7cedf924e753
Revises: 4dcbd08e0b49
Create Date: 2018-11-24 11:14:41.224187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cedf924e753'
down_revision = '4dcbd08e0b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('userPackageID', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'packages', ['package_name'])
    op.drop_constraint('packages_ibfk_1', 'packages', type_='foreignkey')
    op.create_foreign_key(None, 'packages', 'items', ['itemID'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'packages', 'users', ['userPackageID'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'packages', type_='foreignkey')
    op.drop_constraint(None, 'packages', type_='foreignkey')
    op.create_foreign_key('packages_ibfk_1', 'packages', 'items', ['itemID'], ['id'])
    op.drop_constraint(None, 'packages', type_='unique')
    op.drop_column('packages', 'userPackageID')
    # ### end Alembic commands ###
