"""empty message

Revision ID: 9b635c10a552
Revises: 382c2d6321d7
Create Date: 2018-11-23 17:39:54.424755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b635c10a552'
down_revision = '382c2d6321d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('userID', sa.Integer(), nullable=False))
    op.drop_constraint('category_ibfk_1', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'users', ['userID'], ['id'])
    op.drop_column('category', 'userItem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('userItem', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_ibfk_1', 'category', 'items', ['userItem'], ['userItem'])
    op.drop_column('category', 'userID')
    # ### end Alembic commands ###
