"""empty message

Revision ID: a5acdd7d76c4
Revises: 21316d122208
Create Date: 2018-11-27 06:21:00.812620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5acdd7d76c4'
down_revision = '21316d122208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actual_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('packageActualStocksID', sa.Integer(), nullable=False),
    sa.Column('actual_stock', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['packageActualStocksID'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stocks')
    op.drop_table('po_details')
    op.drop_table('adjustments')
    op.add_column('PO', sa.Column('buyingPricePerPackage', sa.Float(), nullable=True))
    op.add_column('PO', sa.Column('packagePOID', sa.Integer(), nullable=False))
    op.add_column('PO', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('PO', sa.Column('totalPrice', sa.Float(), nullable=True))
    op.add_column('PO', sa.Column('userPOID', sa.Integer(), nullable=False))
    op.drop_constraint('PO_ibfk_1', 'PO', type_='foreignkey')
    op.create_foreign_key(None, 'PO', 'packages', ['packagePOID'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'PO', 'users', ['userPOID'], ['id'], ondelete='CASCADE')
    op.drop_column('PO', 'total')
    op.drop_column('PO', 'stockID')
    op.add_column('sales', sa.Column('packageSalesID', sa.Integer(), nullable=False))
    op.add_column('sales', sa.Column('sellingPricePerPackage', sa.Float(), nullable=False))
    op.add_column('sales', sa.Column('totalPrice', sa.Float(), nullable=True))
    op.drop_constraint('sales_ibfk_2', 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'packages', ['packageSalesID'], ['id'], ondelete='CASCADE')
    op.drop_column('sales', 'stockSalesID')
    op.drop_column('sales', 'sellingPrice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('sellingPrice', mysql.FLOAT(), nullable=False))
    op.add_column('sales', sa.Column('stockSalesID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key('sales_ibfk_2', 'sales', 'stocks', ['stockSalesID'], ['id'], ondelete='CASCADE')
    op.drop_column('sales', 'totalPrice')
    op.drop_column('sales', 'sellingPricePerPackage')
    op.drop_column('sales', 'packageSalesID')
    op.add_column('PO', sa.Column('stockID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('PO', sa.Column('total', mysql.FLOAT(), nullable=True))
    op.drop_constraint(None, 'PO', type_='foreignkey')
    op.drop_constraint(None, 'PO', type_='foreignkey')
    op.create_foreign_key('PO_ibfk_1', 'PO', 'stocks', ['stockID'], ['id'], ondelete='CASCADE')
    op.drop_column('PO', 'userPOID')
    op.drop_column('PO', 'totalPrice')
    op.drop_column('PO', 'quantity')
    op.drop_column('PO', 'packagePOID')
    op.drop_column('PO', 'buyingPricePerPackage')
    op.create_table('adjustments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('userAdjustmentsID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('stockAdjustmentsID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('actualStocks', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('notes', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['stockAdjustmentsID'], ['stocks.id'], name='adjustments_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userAdjustmentsID'], ['users.id'], name='adjustments_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('po_details',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('POID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('packageID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('packageName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('inStock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('unitCost', mysql.FLOAT(), nullable=True),
    sa.Column('subTotal', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['POID'], ['PO.id'], name='po_details_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['packageID'], ['packages.id'], name='po_details_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('stocks',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('packagesID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('beginning', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('adjustment', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sale', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('userStocksID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('purchaseOrder', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['packagesID'], ['packages.id'], name='stocks_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userStocksID'], ['users.id'], name='stocks_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('actual_stock')
    # ### end Alembic commands ###
