"""empty message

Revision ID: c3923b9e1cd4
Revises: 056faa9cefb6
Create Date: 2018-11-26 10:25:18.868279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3923b9e1cd4'
down_revision = '056faa9cefb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userAdjustmentsID', sa.Integer(), nullable=False),
    sa.Column('stockAdjustmentsID', sa.Integer(), nullable=False),
    sa.Column('actualStocks', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stockAdjustmentsID'], ['stocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userAdjustmentsID'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('po_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('POID', sa.Integer(), nullable=False),
    sa.Column('packageID', sa.Integer(), nullable=False),
    sa.Column('packageName', sa.String(length=255), nullable=True),
    sa.Column('inStock', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('unitCost', sa.Float(), nullable=True),
    sa.Column('subTotal', sa.Float(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['POID'], ['PO.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['packageID'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('PODetails')
    op.drop_index('package_name', table_name='packages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('package_name', 'packages', ['package_name'], unique=True)
    op.create_table('PODetails',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('POID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('packageID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('packageName', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('inStock', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('unitCost', mysql.FLOAT(), nullable=True),
    sa.Column('subTotal', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['POID'], ['PO.id'], name='PODetails_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['packageID'], ['packages.id'], name='PODetails_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('po_details')
    op.drop_table('adjustments')
    # ### end Alembic commands ###
