"""empty message

Revision ID: c9373045e68d
Revises: 59438e891798
Create Date: 2018-11-25 13:49:33.514022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9373045e68d'
down_revision = '59438e891798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('POdetails',
    sa.Column('POID', sa.Integer(), nullable=False),
    sa.Column('packageID', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=50), nullable=True),
    sa.Column('inStock', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('unitCost', sa.Float(), nullable=True),
    sa.Column('subTotal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['POID'], ['PO.id'], ),
    sa.ForeignKeyConstraint(['packageID'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('POID', 'packageID')
    )
    op.add_column('PO', sa.Column('total', sa.Float(), nullable=True))
    op.drop_column('PO', 'quantity')
    op.drop_column('PO', 'purchase_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PO', sa.Column('purchase_price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('PO', sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('PO', 'total')
    op.drop_table('POdetails')
    # ### end Alembic commands ###
