"""empty message

Revision ID: cd1e7036e4e0
Revises: c3923b9e1cd4
Create Date: 2018-11-26 13:27:37.234251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd1e7036e4e0'
down_revision = 'c3923b9e1cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('category', table_name='category')
    op.add_column('stocks', sa.Column('adjustment', sa.Integer(), nullable=True))
    op.add_column('stocks', sa.Column('sale', sa.Integer(), nullable=True))
    op.add_column('stocks', sa.Column('userStocksID', sa.Integer(), nullable=False))
    op.alter_column('stocks', 'beginning',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_foreign_key(None, 'stocks', 'users', ['userStocksID'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.alter_column('stocks', 'beginning',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('stocks', 'userStocksID')
    op.drop_column('stocks', 'sale')
    op.drop_column('stocks', 'adjustment')
    op.create_index('category', 'category', ['category'], unique=True)
    # ### end Alembic commands ###
