"""empty message

Revision ID: e784fef10867
Revises: 4d54ec49ec5e
Create Date: 2018-11-27 10:16:00.718087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e784fef10867'
down_revision = '4d54ec49ec5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actual_stock', sa.Column('userActualStocksID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'actual_stock', 'users', ['userActualStocksID'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actual_stock', type_='foreignkey')
    op.drop_column('actual_stock', 'userActualStocksID')
    # ### end Alembic commands ###
