"""empty message

Revision ID: eb08e113cf6c
Revises: 9b635c10a552
Create Date: 2018-11-23 17:57:00.770763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb08e113cf6c'
down_revision = '9b635c10a552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('userID', sa.Integer(), nullable=False))
    op.drop_constraint('items_ibfk_2', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'users', ['userID'], ['id'], ondelete='CASCADE')
    op.drop_column('items', 'userItem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('userItem', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_ibfk_2', 'items', 'users', ['userItem'], ['id'], ondelete='CASCADE')
    op.drop_column('items', 'userID')
    # ### end Alembic commands ###
